name = "beer"


[task.build]
command = "go build ."
description = "Build the project"
depends = [
    "generate",
]

[task.format]
command = "go fmt ./..."
description = "Format the project"

[task.generate]
command = "go generate ./..."
description = "Go generate"

[task.test]
command = "go test ./... -test.fullpath -timeout 1000ms -failfast"
description = "Test the project"
depends = [
    "build"
]
