// Code generated by "stringer -type=Type"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Integer-0]
	_ = x[Float-1]
	_ = x[String-2]
	_ = x[Boolean-3]
	_ = x[Void-4]
	_ = x[Illegal-5]
}

const _Type_name = "IntegerFloatStringBooleanVoidIllegal"

var _Type_index = [...]uint8{0, 7, 12, 18, 25, 29, 36}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
